import 'package:flutter/material.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget2/generated/GeneratedVectorWidget45.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget2/generated/GeneratedThuanydeSouzaWidget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget2/generated/GeneratedRectangle5Widget2.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget2/generated/GeneratedCertificadosparaavaliarWidget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget2/generated/GeneratedLine1Widget2.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget2/generated/GeneratedImage3Widget2.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget2/generated/GeneratedNotificationWidget8.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget2/generated/GeneratedBrunoMeslinWidget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget2/generated/GeneratedImage1Widget2.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget2/generated/GeneratedNewPendenteWidget1.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget2/generated/GeneratedPendenteWidget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget2/generated/GeneratedRectangle7Widget4.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget2/generated/GeneratedOlcoordenadorWidget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget2/generated/GeneratedCarlosLealWidget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget2/generated/Generated25Widget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget2/generated/GeneratedImage2Widget2.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget2/generated/GeneratedRectangle9Widget1.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget2/generated/GeneratedNewPendenteWidget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget2/generated/GeneratedRectangle4Widget2.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget2/generated/GeneratedCursodeDesignAplicadoWidget4.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget2/generated/GeneratedArrowbackiosWidget3.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget2/generated/GeneratedNotificationWidget9.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget2/generated/GeneratedRectangle6Widget2.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget2/generated/GeneratedVectorWidget44.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget2/generated/GeneratedAlunosWidget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget2/generated/Generated20hWidget6.dart';

/* Frame 3.Inicial
    Autogenerated by FlutLab FTF Generator
  */
class Generated3InicialWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            clipBehavior: Clip.none, fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 32, 44, 51),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 110.0,
                child: GeneratedRectangle4Widget2(),
              ),
              Positioned(
                left: 25.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 21.0,
                child: GeneratedNotificationWidget8(),
              ),
              Positioned(
                left: 25.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 21.0,
                child: GeneratedNotificationWidget9(),
              ),
              Positioned(
                left: 25.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 30.0,
                child: GeneratedOlcoordenadorWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 324.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 133.0,
                child: GeneratedRectangle5Widget2(),
              ),
              Positioned(
                left: 19.0,
                top: 190.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 107.0,
                child: GeneratedRectangle9Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 324.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 87.0,
                child: GeneratedImage1Widget2(),
              ),
              Positioned(
                left: 234.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 227.0,
                height: 23.0,
                child: GeneratedThuanydeSouzaWidget(),
              ),
              Positioned(
                left: 29.0,
                top: 734.0,
                right: null,
                bottom: null,
                width: 230.0,
                height: 26.0,
                child: GeneratedPendenteWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 479.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 133.0,
                child: GeneratedRectangle6Widget2(),
              ),
              Positioned(
                left: 21.0,
                top: 634.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 133.0,
                child: GeneratedRectangle7Widget4(),
              ),
              Positioned(
                left: 20.0,
                top: 479.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 87.0,
                child: GeneratedImage2Widget2(),
              ),
              Positioned(
                left: 21.0,
                top: 634.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 87.0,
                child: GeneratedImage3Widget2(),
              ),
              Positioned(
                left: 29.0,
                top: 576.0,
                right: null,
                bottom: null,
                width: 230.0,
                height: 41.0,
                child: GeneratedNewPendenteWidget(),
              ),
              Positioned(
                left: 40.0,
                top: 419.0,
                right: null,
                bottom: null,
                width: 230.0,
                height: 41.0,
                child: GeneratedNewPendenteWidget1(),
              ),
              Positioned(
                left: 263.0,
                top: 581.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 20.0,
                child: GeneratedCarlosLealWidget(),
              ),
              Positioned(
                left: 263.0,
                top: 738.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 20.0,
                child: GeneratedBrunoMeslinWidget(),
              ),
              Positioned(
                left: 29.0,
                top: 868.0,
                right: null,
                bottom: null,
                width: 227.0,
                height: 23.0,
                child: GeneratedCursodeDesignAplicadoWidget4(),
              ),
              Positioned(
                left: 322.0,
                top: 873.0,
                right: null,
                bottom: null,
                width: 29.0,
                height: 23.0,
                child: Generated20hWidget6(),
              ),
              Positioned(
                left: 21.0,
                top: 133.0,
                right: null,
                bottom: null,
                width: 155.0,
                height: 20.0,
                child: GeneratedCertificadosparaavaliarWidget(),
              ),
              Positioned(
                left: 320.0,
                top: 134.0,
                right: null,
                bottom: null,
                width: 111.0,
                height: 24.0,
                child: Generated25Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 153.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 1.0,
                child: GeneratedLine1Widget2(),
              ),
              Positioned(
                left: 54.0,
                top: 213.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedVectorWidget44(),
              ),
              Positioned(
                left: 54.0,
                top: 213.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedVectorWidget45(),
              ),
              Positioned(
                left: 121.0,
                top: 205.0,
                right: null,
                bottom: null,
                width: 222.0,
                height: 65.0,
                child: GeneratedAlunosWidget(),
              ),
              Positioned(
                left: 10.0,
                top: 29.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 31.0,
                child: GeneratedArrowbackiosWidget3(),
              )
            ]),
      ),
    ));
  }
}
