import 'package:flutter/material.dart';

/* Text Aprovado pelo coordenador
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAprovadopelocoordenadorWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''Aprovado pelo coordenador''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.5,
        fontSize: 19.0,
        fontFamily: 'Poppins',
        fontWeight: FontWeight.w600,
        color: Color.fromARGB(255, 255, 255, 255),

        /* letterSpacing: 0.0, */
      ),
    ));
  }
}
