import 'package:flutter/material.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget/generated/GeneratedRectangle7Widget2.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget/generated/GeneratedArrowbackiosWidget1.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget/generated/GeneratedCursodeDesignAplicadoWidget1.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget/generated/GeneratedOlalunoWidget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget/generated/GeneratedLine1Widget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget/generated/Generated200hWidget1.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget/generated/GeneratedImage1Widget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget/generated/GeneratedVectorWidget21.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget/generated/Generated20hWidget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget/generated/GeneratedPalestraDesign20Widget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget/generated/GeneratedNotificationWidget5.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget/generated/Generated260hWidget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget/generated/GeneratedCursodeDesignWidget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget/generated/GeneratedCursodeDesignAplicadoWidget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget/generated/GeneratedTotaldehorascomplementaresWidget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget/generated/GeneratedEmanlisecomocorrdenadorWidget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget/generated/GeneratedImage3Widget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget/generated/GeneratedNotificationWidget4.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget/generated/GeneratedVectorWidget22.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget/generated/GeneratedImage2Widget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget/generated/Generated20hWidget2.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget/generated/Generated20hWidget1.dart';

/* Frame 3.Inicial
    Autogenerated by FlutLab FTF Generator
  */
class Generated3InicialWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            clipBehavior: Clip.none, fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 32, 44, 51),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 110.0,
                child: GeneratedRectangle4Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 21.0,
                child: GeneratedNotificationWidget4(),
              ),
              Positioned(
                left: 25.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 21.0,
                child: GeneratedNotificationWidget5(),
              ),
              Positioned(
                left: 25.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 30.0,
                child: GeneratedOlalunoWidget(),
              ),
              Positioned(
                left: 323.0,
                top: 58.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedVectorWidget21(),
              ),
              Positioned(
                left: 20.0,
                top: 327.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 133.0,
                child: GeneratedRectangle5Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 193.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 107.0,
                child: GeneratedRectangle9Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 327.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 87.0,
                child: GeneratedImage1Widget(),
              ),
              Positioned(
                left: 29.0,
                top: 424.0,
                right: null,
                bottom: null,
                width: 227.0,
                height: 23.0,
                child: GeneratedCursodeDesignWidget(),
              ),
              Positioned(
                left: 315.0,
                top: 402.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 23.0,
                child: Generated200hWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 482.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 133.0,
                child: GeneratedRectangle6Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 637.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 133.0,
                child: GeneratedRectangle7Widget2(),
              ),
              Positioned(
                left: 20.0,
                top: 482.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 87.0,
                child: GeneratedImage2Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 637.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 87.0,
                child: GeneratedImage3Widget(),
              ),
              Positioned(
                left: 29.0,
                top: 579.0,
                right: null,
                bottom: null,
                width: 227.0,
                height: 23.0,
                child: GeneratedPalestraDesign20Widget(),
              ),
              Positioned(
                left: 29.0,
                top: 736.0,
                right: null,
                bottom: null,
                width: 227.0,
                height: 23.0,
                child: GeneratedCursodeDesignAplicadoWidget(),
              ),
              Positioned(
                left: 322.0,
                top: 557.0,
                right: null,
                bottom: null,
                width: 29.0,
                height: 23.0,
                child: Generated20hWidget(),
              ),
              Positioned(
                left: 322.0,
                top: 714.0,
                right: null,
                bottom: null,
                width: 29.0,
                height: 23.0,
                child: Generated20hWidget1(),
              ),
              Positioned(
                left: 29.0,
                top: 868.0,
                right: null,
                bottom: null,
                width: 227.0,
                height: 23.0,
                child: GeneratedCursodeDesignAplicadoWidget1(),
              ),
              Positioned(
                left: 322.0,
                top: 873.0,
                right: null,
                bottom: null,
                width: 29.0,
                height: 23.0,
                child: Generated20hWidget2(),
              ),
              Positioned(
                left: 21.0,
                top: 133.0,
                right: null,
                bottom: null,
                width: 198.0,
                height: 20.0,
                child: GeneratedTotaldehorascomplementaresWidget(),
              ),
              Positioned(
                left: 320.0,
                top: 134.0,
                right: null,
                bottom: null,
                width: 111.0,
                height: 24.0,
                child: Generated260hWidget(),
              ),
              Positioned(
                left: 19.0,
                top: 153.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 1.0,
                child: GeneratedLine1Widget(),
              ),
              Positioned(
                left: 54.0,
                top: 216.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedVectorWidget22(),
              ),
              Positioned(
                left: 114.0,
                top: 216.0,
                right: null,
                bottom: null,
                width: 219.0,
                height: 62.0,
                child: GeneratedEmanlisecomocorrdenadorWidget(),
              ),
              Positioned(
                left: 10.0,
                top: 29.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 31.0,
                child: GeneratedArrowbackiosWidget1(),
              )
            ]),
      ),
    ));
  }
}
