import 'package:flutter/material.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget3/generated/GeneratedRectangle7Widget6.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget3/generated/GeneratedButtonWidget15.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget3/generated/Generated451621Widget2.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget3/generated/GeneratedButtonWidget16.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget3/generated/GeneratedNotificationWidget18.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget3/generated/GeneratedLogocatolica3Widget3.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget3/generated/GeneratedCertificadosWidget2.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget3/generated/GeneratedNotificationWidget19.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget3/generated/GeneratedButtonWidget17.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget3/generated/GeneratedFrame1Widget3.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget3/generated/GeneratedArrowbackiosWidget7.dart';

/* Frame 4.Scanning
    Autogenerated by FlutLab FTF Generator
  */
class Generated4ScanningWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            clipBehavior: Clip.none, fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 32, 44, 51),
                ),
              ),
              Positioned(
                left: 25.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 21.0,
                child: GeneratedNotificationWidget18(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 110.0,
                child: GeneratedRectangle7Widget6(),
              ),
              Positioned(
                left: 170.0,
                top: 761.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 40.0,
                child: GeneratedLogocatolica3Widget3(),
              ),
              Positioned(
                left: 21.0,
                top: 5.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 21.0,
                child: GeneratedNotificationWidget19(),
              ),
              Positioned(
                left: 50.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedFrame1Widget3(),
              ),
              Positioned(
                left: 25.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 33.0,
                child: GeneratedCertificadosWidget2(),
              ),
              Positioned(
                left: 25.0,
                top: 200.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 60.0,
                child: GeneratedButtonWidget15(),
              ),
              Positioned(
                left: 26.0,
                top: 318.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 60.0,
                child: GeneratedButtonWidget16(),
              ),
              Positioned(
                left: 26.0,
                top: 445.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 60.0,
                child: GeneratedButtonWidget17(),
              ),
              Positioned(
                left: 213.0,
                top: 463.0,
                right: null,
                bottom: null,
                width: 23.0,
                height: 23.0,
                child: Generated451621Widget2(),
              ),
              Positioned(
                left: 6.0,
                top: 27.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 31.0,
                child: GeneratedArrowbackiosWidget7(),
              )
            ]),
      ),
    ));
  }
}
