import 'package:flutter/material.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget4/generated/GeneratedCertificadosWidget3.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget4/generated/GeneratedButtonWidget19.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget4/generated/GeneratedNotificationWidget21.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget4/generated/GeneratedButtonWidget18.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget4/generated/GeneratedNotificationWidget20.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget4/generated/GeneratedFrame1Widget4.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget4/generated/GeneratedLogocatolica3Widget4.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget4/generated/GeneratedButtonWidget20.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget4/generated/GeneratedArrowbackiosWidget8.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget4/generated/GeneratedRectangle7Widget7.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget4/generated/Generated451621Widget3.dart';

/* Frame 4.Scanning
    Autogenerated by FlutLab FTF Generator
  */
class Generated4ScanningWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            clipBehavior: Clip.none, fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 32, 44, 51),
                ),
              ),
              Positioned(
                left: 25.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 21.0,
                child: GeneratedNotificationWidget20(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 110.0,
                child: GeneratedRectangle7Widget7(),
              ),
              Positioned(
                left: 170.0,
                top: 761.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 40.0,
                child: GeneratedLogocatolica3Widget4(),
              ),
              Positioned(
                left: 21.0,
                top: 5.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 21.0,
                child: GeneratedNotificationWidget21(),
              ),
              Positioned(
                left: 50.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedFrame1Widget4(),
              ),
              Positioned(
                left: 25.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 33.0,
                child: GeneratedCertificadosWidget3(),
              ),
              Positioned(
                left: 25.0,
                top: 200.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 60.0,
                child: GeneratedButtonWidget18(),
              ),
              Positioned(
                left: 26.0,
                top: 318.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 60.0,
                child: GeneratedButtonWidget19(),
              ),
              Positioned(
                left: 26.0,
                top: 445.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 60.0,
                child: GeneratedButtonWidget20(),
              ),
              Positioned(
                left: 213.0,
                top: 463.0,
                right: null,
                bottom: null,
                width: 23.0,
                height: 23.0,
                child: Generated451621Widget3(),
              ),
              Positioned(
                left: 10.0,
                top: 29.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 31.0,
                child: GeneratedArrowbackiosWidget8(),
              )
            ]),
      ),
    ));
  }
}
