import 'package:flutter/material.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget1/generated/GeneratedNotificationWidget2.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget1/generated/GeneratedRectangle7Widget1.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget1/generated/GeneratedFrame1Widget1.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget1/generated/Generated451621Widget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget1/generated/GeneratedButtonWidget6.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget1/generated/GeneratedNotificationWidget3.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget1/generated/GeneratedButtonWidget4.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget1/generated/GeneratedArrowbackiosWidget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget1/generated/GeneratedCertificadosWidget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget1/generated/GeneratedButtonWidget5.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget1/generated/GeneratedLogocatolica3Widget1.dart';

/* Frame 4.Scanning
    Autogenerated by FlutLab FTF Generator
  */
class Generated4ScanningWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            clipBehavior: Clip.none, fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 32, 44, 51),
                ),
              ),
              Positioned(
                left: 25.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 21.0,
                child: GeneratedNotificationWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 110.0,
                child: GeneratedRectangle7Widget1(),
              ),
              Positioned(
                left: 170.0,
                top: 761.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 40.0,
                child: GeneratedLogocatolica3Widget1(),
              ),
              Positioned(
                left: 21.0,
                top: 5.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 21.0,
                child: GeneratedNotificationWidget3(),
              ),
              Positioned(
                left: 50.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedFrame1Widget1(),
              ),
              Positioned(
                left: 25.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 33.0,
                child: GeneratedCertificadosWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 200.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 60.0,
                child: GeneratedButtonWidget4(),
              ),
              Positioned(
                left: 26.0,
                top: 318.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 60.0,
                child: GeneratedButtonWidget5(),
              ),
              Positioned(
                left: 26.0,
                top: 445.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 60.0,
                child: GeneratedButtonWidget6(),
              ),
              Positioned(
                left: 213.0,
                top: 463.0,
                right: null,
                bottom: null,
                width: 23.0,
                height: 23.0,
                child: Generated451621Widget(),
              ),
              Positioned(
                left: 6.0,
                top: 29.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 31.0,
                child: GeneratedArrowbackiosWidget(),
              )
            ]),
      ),
    ));
  }
}
