import 'package:flutter/material.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget4/generated/GeneratedNotificationWidget14.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget4/generated/GeneratedLine1Widget4.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget4/generated/GeneratedRectangle4Widget4.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget4/generated/GeneratedRectangle14Widget1.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget4/generated/GeneratedAlunosWidget2.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget4/generated/GeneratedVectorWidget80.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget4/generated/Generated20hWidget8.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget4/generated/GeneratedRectangle12Widget1.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget4/generated/GeneratedRectangle10Widget1.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget4/generated/GeneratedVectorWidget85.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget4/generated/GeneratedNotificationWidget15.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget4/generated/GeneratedVectorWidget79.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget4/generated/GeneratedCarlosLealWidget1.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget4/generated/GeneratedVectorWidget81.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget4/generated/GeneratedRectangle15Widget1.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget4/generated/GeneratedCursodeDesignAplicadoWidget6.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget4/generated/GeneratedVectorWidget82.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget4/generated/GeneratedAdemilsonChagasWidget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget4/generated/GeneratedThuanydeSouzaWidget1.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget4/generated/GeneratedRectangle9Widget3.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget4/generated/GeneratedBrunoMeslinWidget1.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget4/generated/GeneratedRectangle13Widget1.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget4/generated/GeneratedRectangle16Widget1.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget4/generated/GeneratedArrowbackiosWidget6.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget4/generated/GeneratedVectorWidget78.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget4/generated/GeneratedRectangle11Widget1.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget4/generated/GeneratedVectorWidget84.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget4/generated/GeneratedVectorWidget83.dart';

/* Frame 3.Inicial
    Autogenerated by FlutLab FTF Generator
  */
class Generated3InicialWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            clipBehavior: Clip.none, fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 32, 44, 51),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 110.0,
                child: GeneratedRectangle4Widget4(),
              ),
              Positioned(
                left: 25.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 21.0,
                child: GeneratedNotificationWidget14(),
              ),
              Positioned(
                left: 25.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 21.0,
                child: GeneratedNotificationWidget15(),
              ),
              Positioned(
                left: 25.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 197.0,
                height: 33.0,
                child: GeneratedAlunosWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 202.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 107.0,
                child: GeneratedRectangle9Widget3(),
              ),
              Positioned(
                left: 20.0,
                top: 202.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 107.0,
                child: GeneratedRectangle10Widget1(),
              ),
              Positioned(
                left: 29.0,
                top: 868.0,
                right: null,
                bottom: null,
                width: 227.0,
                height: 23.0,
                child: GeneratedCursodeDesignAplicadoWidget6(),
              ),
              Positioned(
                left: 322.0,
                top: 873.0,
                right: null,
                bottom: null,
                width: 29.0,
                height: 23.0,
                child: Generated20hWidget8(),
              ),
              Positioned(
                left: 19.0,
                top: 153.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 1.0,
                child: GeneratedLine1Widget4(),
              ),
              Positioned(
                left: 55.0,
                top: 225.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedVectorWidget78(),
              ),
              Positioned(
                left: 55.0,
                top: 225.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedVectorWidget79(),
              ),
              Positioned(
                left: 122.0,
                top: 241.0,
                right: null,
                bottom: null,
                width: 219.0,
                height: 62.0,
                child: GeneratedAdemilsonChagasWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 335.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 107.0,
                child: GeneratedRectangle11Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 335.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 107.0,
                child: GeneratedRectangle12Widget1(),
              ),
              Positioned(
                left: 55.0,
                top: 358.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedVectorWidget80(),
              ),
              Positioned(
                left: 55.0,
                top: 358.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedVectorWidget81(),
              ),
              Positioned(
                left: 122.0,
                top: 374.0,
                right: null,
                bottom: null,
                width: 219.0,
                height: 62.0,
                child: GeneratedBrunoMeslinWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 476.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 107.0,
                child: GeneratedRectangle13Widget1(),
              ),
              Positioned(
                left: 22.0,
                top: 475.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 107.0,
                child: GeneratedRectangle14Widget1(),
              ),
              Positioned(
                left: 55.0,
                top: 499.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedVectorWidget82(),
              ),
              Positioned(
                left: 55.0,
                top: 499.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedVectorWidget83(),
              ),
              Positioned(
                left: 122.0,
                top: 515.0,
                right: null,
                bottom: null,
                width: 219.0,
                height: 62.0,
                child: GeneratedCarlosLealWidget1(),
              ),
              Positioned(
                left: 18.0,
                top: 617.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 107.0,
                child: GeneratedRectangle15Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 617.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 107.0,
                child: GeneratedRectangle16Widget1(),
              ),
              Positioned(
                left: 53.0,
                top: 640.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedVectorWidget84(),
              ),
              Positioned(
                left: 53.0,
                top: 640.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedVectorWidget85(),
              ),
              Positioned(
                left: 120.0,
                top: 656.0,
                right: null,
                bottom: null,
                width: 219.0,
                height: 62.0,
                child: GeneratedThuanydeSouzaWidget1(),
              ),
              Positioned(
                left: 10.0,
                top: 29.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 31.0,
                child: GeneratedArrowbackiosWidget6(),
              )
            ]),
      ),
    ));
  }
}
