import 'package:flutter/material.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget/generated/GeneratedButtonWidget3.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget/generated/GeneratedButtonWidget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget/generated/GeneratedButtonWidget2.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget/generated/GeneratedButtonWidget1.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget/generated/GeneratedLogocatolica3Widget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget/generated/GeneratedAdicionarcertificadoWidget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget/generated/GeneratedFrame1Widget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget/generated/GeneratedNotificationWidget1.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget/generated/GeneratedVectorWidget6.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget/generated/GeneratedCancelarWidget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget/generated/GeneratedNotificationWidget.dart';

/* Frame 4.Scanning
    Autogenerated by FlutLab FTF Generator
  */
class Generated4ScanningWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            clipBehavior: Clip.none, fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 32, 44, 51),
                ),
              ),
              Positioned(
                left: 25.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 21.0,
                child: GeneratedNotificationWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 110.0,
                child: GeneratedRectangle7Widget(),
              ),
              Positioned(
                left: 170.0,
                top: 761.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 40.0,
                child: GeneratedLogocatolica3Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 5.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 21.0,
                child: GeneratedNotificationWidget1(),
              ),
              Positioned(
                left: 50.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedFrame1Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 317.0,
                height: 30.0,
                child: GeneratedAdicionarcertificadoWidget(),
              ),
              Positioned(
                left: 26.0,
                top: 148.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 60.0,
                child: GeneratedButtonWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 229.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 60.0,
                child: GeneratedButtonWidget1(),
              ),
              Positioned(
                left: 24.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 60.0,
                child: GeneratedButtonWidget2(),
              ),
              Positioned(
                left: 234.0,
                top: 326.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 23.0,
                child: GeneratedVectorWidget6(),
              ),
              Positioned(
                left: 25.0,
                top: 424.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 60.0,
                child: GeneratedButtonWidget3(),
              ),
              Positioned(
                left: 82.0,
                top: 505.0,
                right: null,
                bottom: null,
                width: 206.0,
                height: 41.0,
                child: GeneratedCancelarWidget(),
              )
            ]),
      ),
    ));
  }
}
