import 'package:flutter/material.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget2/generated/GeneratedButtonWidget8.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget2/generated/GeneratedCertificadosWidget1.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget2/generated/GeneratedButtonWidget7.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget2/generated/GeneratedLogocatolica3Widget2.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget2/generated/GeneratedFrame1Widget2.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget2/generated/GeneratedButtonWidget11.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget2/generated/GeneratedRectangle7Widget5.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget2/generated/GeneratedNotificationWidget11.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget2/generated/Generated451621Widget1.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget2/generated/GeneratedNotificationWidget10.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget2/generated/GeneratedButtonWidget9.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget2/generated/GeneratedButtonWidget10.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget2/generated/GeneratedFrame2Widget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated4scanningwidget2/generated/GeneratedArrowbackiosWidget4.dart';

/* Frame 4.Scanning
    Autogenerated by FlutLab FTF Generator
  */
class Generated4ScanningWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            clipBehavior: Clip.none, fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 32, 44, 51),
                ),
              ),
              Positioned(
                left: 25.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 21.0,
                child: GeneratedNotificationWidget10(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 110.0,
                child: GeneratedRectangle7Widget5(),
              ),
              Positioned(
                left: 170.0,
                top: 761.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 40.0,
                child: GeneratedLogocatolica3Widget2(),
              ),
              Positioned(
                left: 21.0,
                top: 5.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 21.0,
                child: GeneratedNotificationWidget11(),
              ),
              Positioned(
                left: 50.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedFrame1Widget2(),
              ),
              Positioned(
                left: 25.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 33.0,
                child: GeneratedCertificadosWidget1(),
              ),
              Positioned(
                left: 25.0,
                top: 200.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 60.0,
                child: GeneratedButtonWidget7(),
              ),
              Positioned(
                left: 25.0,
                top: 313.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 60.0,
                child: GeneratedButtonWidget8(),
              ),
              Positioned(
                left: 47.0,
                top: 496.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedFrame2Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 596.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 60.0,
                child: GeneratedButtonWidget9(),
              ),
              Positioned(
                left: 26.0,
                top: 426.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 60.0,
                child: GeneratedButtonWidget10(),
              ),
              Positioned(
                left: 214.0,
                top: 441.0,
                right: null,
                bottom: null,
                width: 23.0,
                height: 23.0,
                child: Generated451621Widget1(),
              ),
              Positioned(
                left: 26.0,
                top: 684.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 60.0,
                child: GeneratedButtonWidget11(),
              ),
              Positioned(
                left: 10.0,
                top: 29.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 31.0,
                child: GeneratedArrowbackiosWidget4(),
              )
            ]),
      ),
    ));
  }
}
