import 'package:flutter/material.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated2loginwidget/generated/GeneratedNotificationWidget16.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated2loginwidget/generated/GeneratedButtonWidget12.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated2loginwidget/generated/GeneratedLogocatolicacor1Widget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated2loginwidget/generated/GeneratedLogocatolica2Widget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated2loginwidget/generated/GeneratedCHCWidget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated2loginwidget/generated/GeneratedButtonWidget13.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated2loginwidget/generated/GeneratedButtonWidget14.dart';

/* Frame 2.Login
    Autogenerated by FlutLab FTF Generator
  */
class Generated2LoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            clipBehavior: Clip.none, fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 36, 49, 57),
                ),
              ),
              Positioned(
                left: 25.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 21.0,
                child: GeneratedNotificationWidget16(),
              ),
              Positioned(
                left: 24.0,
                top: 559.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 60.0,
                child: GeneratedButtonWidget12(),
              ),
              Positioned(
                left: 25.0,
                top: 365.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 60.0,
                child: GeneratedButtonWidget13(),
              ),
              Positioned(
                left: 24.0,
                top: 446.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 60.0,
                child: GeneratedButtonWidget14(),
              ),
              Positioned(
                left: 145.0,
                top: 270.0,
                right: null,
                bottom: null,
                width: 84.0,
                height: 95.02362823486328,
                child: GeneratedLogocatolica2Widget(),
              ),
              Positioned(
                left: 129.0,
                top: 141.0,
                right: null,
                bottom: null,
                width: 114.72688293457031,
                height: 119.0,
                child: GeneratedLogocatolicacor1Widget(),
              ),
              Positioned(
                left: 163.0,
                top: 294.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 33.0,
                child: GeneratedCHCWidget(),
              )
            ]),
      ),
    ));
  }
}
