import 'package:flutter/material.dart';

/* Rectangle Rectangle 19
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRectangle19Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 115.0,
      height: 53.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(8.0),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(8.0),
        child: Container(
          color: Color.fromARGB(255, 5, 255, 0),
        ),
      ),
    ));
  }
}
