import 'package:flutter/material.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget3/generated/GeneratedNotificationWidget13.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget3/generated/GeneratedNotificationWidget12.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget3/generated/GeneratedLine1Widget3.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget3/generated/Generated3semestreWidget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget3/generated/Generated1semestreWidget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget3/generated/GeneratedVectorWidget68.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget3/generated/GeneratedVectorWidget63.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget3/generated/Generated2semestreWidget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget3/generated/GeneratedVectorWidget66.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget3/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget3/generated/GeneratedRectangle10Widget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget3/generated/GeneratedRectangle9Widget2.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget3/generated/GeneratedRectangle4Widget3.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget3/generated/GeneratedVectorWidget64.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget3/generated/GeneratedVectorWidget62.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget3/generated/Generated20hWidget7.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget3/generated/GeneratedVectorWidget65.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget3/generated/GeneratedCursodeDesignAplicadoWidget5.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget3/generated/GeneratedVectorWidget67.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget3/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget3/generated/GeneratedArrowbackiosWidget5.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget3/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget3/generated/GeneratedRectangle11Widget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget3/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget3/generated/GeneratedVectorWidget69.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget3/generated/Generated4semestreWidget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget3/generated/GeneratedAlunosWidget1.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget3/generated/GeneratedRectangle13Widget.dart';

/* Frame 3.Inicial
    Autogenerated by FlutLab FTF Generator
  */
class Generated3InicialWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            clipBehavior: Clip.none, fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 32, 44, 51),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 110.0,
                child: GeneratedRectangle4Widget3(),
              ),
              Positioned(
                left: 25.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 21.0,
                child: GeneratedNotificationWidget12(),
              ),
              Positioned(
                left: 25.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 21.0,
                child: GeneratedNotificationWidget13(),
              ),
              Positioned(
                left: 25.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 197.0,
                height: 33.0,
                child: GeneratedAlunosWidget1(),
              ),
              Positioned(
                left: 19.0,
                top: 204.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 107.0,
                child: GeneratedRectangle9Widget2(),
              ),
              Positioned(
                left: 19.0,
                top: 204.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 107.0,
                child: GeneratedRectangle10Widget(),
              ),
              Positioned(
                left: 29.0,
                top: 868.0,
                right: null,
                bottom: null,
                width: 227.0,
                height: 23.0,
                child: GeneratedCursodeDesignAplicadoWidget5(),
              ),
              Positioned(
                left: 322.0,
                top: 873.0,
                right: null,
                bottom: null,
                width: 29.0,
                height: 23.0,
                child: Generated20hWidget7(),
              ),
              Positioned(
                left: 19.0,
                top: 153.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 1.0,
                child: GeneratedLine1Widget3(),
              ),
              Positioned(
                left: 54.0,
                top: 227.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedVectorWidget62(),
              ),
              Positioned(
                left: 54.0,
                top: 227.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedVectorWidget63(),
              ),
              Positioned(
                left: 121.0,
                top: 243.0,
                right: null,
                bottom: null,
                width: 219.0,
                height: 62.0,
                child: Generated1semestreWidget(),
              ),
              Positioned(
                left: 19.0,
                top: 337.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 107.0,
                child: GeneratedRectangle11Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 337.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 107.0,
                child: GeneratedRectangle12Widget(),
              ),
              Positioned(
                left: 54.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedVectorWidget64(),
              ),
              Positioned(
                left: 54.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedVectorWidget65(),
              ),
              Positioned(
                left: 121.0,
                top: 376.0,
                right: null,
                bottom: null,
                width: 219.0,
                height: 62.0,
                child: Generated2semestreWidget(),
              ),
              Positioned(
                left: 19.0,
                top: 478.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 107.0,
                child: GeneratedRectangle13Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 477.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 107.0,
                child: GeneratedRectangle14Widget(),
              ),
              Positioned(
                left: 54.0,
                top: 501.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedVectorWidget66(),
              ),
              Positioned(
                left: 54.0,
                top: 501.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedVectorWidget67(),
              ),
              Positioned(
                left: 121.0,
                top: 517.0,
                right: null,
                bottom: null,
                width: 219.0,
                height: 62.0,
                child: Generated3semestreWidget(),
              ),
              Positioned(
                left: 17.0,
                top: 619.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 107.0,
                child: GeneratedRectangle15Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 619.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 107.0,
                child: GeneratedRectangle16Widget(),
              ),
              Positioned(
                left: 52.0,
                top: 642.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedVectorWidget68(),
              ),
              Positioned(
                left: 52.0,
                top: 642.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedVectorWidget69(),
              ),
              Positioned(
                left: 119.0,
                top: 658.0,
                right: null,
                bottom: null,
                width: 219.0,
                height: 62.0,
                child: Generated4semestreWidget(),
              ),
              Positioned(
                left: 10.0,
                top: 29.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 31.0,
                child: GeneratedArrowbackiosWidget5(),
              )
            ]),
      ),
    ));
  }
}
