import 'package:flutter/material.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated1carregamentowidget/generated/GeneratedNotificationWidget17.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated1carregamentowidget/generated/GeneratedLogocatolica1Widget.dart';

/* Frame 1.Carregamento
    Autogenerated by FlutLab FTF Generator
  */
class Generated1CarregamentoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            clipBehavior: Clip.none, fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 155, 21, 54),
                ),
              ),
              Positioned(
                left: 25.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 21.0,
                child: GeneratedNotificationWidget17(),
              ),
              Positioned(
                left: 145.0,
                top: 358.0,
                right: null,
                bottom: null,
                width: 84.0,
                height: 95.02362823486328,
                child: GeneratedLogocatolica1Widget(),
              )
            ]),
      ),
    ));
  }
}
