import 'package:flutter/material.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget1/generated/GeneratedArrowbackiosWidget2.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget1/generated/GeneratedRectangle4Widget1.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget1/generated/GeneratedVectorWidget35.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget1/generated/GeneratedImage3Widget1.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget1/generated/GeneratedOlalunoWidget1.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget1/generated/GeneratedVectorWidget37.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget1/generated/Generated200hWidget3.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget1/generated/GeneratedRectangle5Widget1.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget1/generated/GeneratedRectangle6Widget1.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget1/generated/GeneratedPalestraDesign20Widget1.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget1/generated/Generated200hWidget2.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget1/generated/GeneratedNotificationWidget7.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget1/generated/GeneratedCursodeDesignAplicadoWidget3.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget1/generated/Generated20hWidget4.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget1/generated/GeneratedEstgionoobrigatrioWidget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget1/generated/GeneratedVectorWidget34.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget1/generated/GeneratedImage1Widget1.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget1/generated/GeneratedCursodeDesignWidget1.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget1/generated/GeneratedRectangle8Widget1.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget1/generated/GeneratedNotificationWidget6.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget1/generated/GeneratedImage2Widget1.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget1/generated/GeneratedRectangle7Widget3.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget1/generated/GeneratedLine1Widget1.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget1/generated/GeneratedImage4Widget.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget1/generated/GeneratedVectorWidget36.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget1/generated/GeneratedCursodeDesignAplicadoWidget2.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget1/generated/Generated20hWidget5.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget1/generated/Generated20hWidget3.dart';
import 'package:flutterapp/telas_flutter_pacapp/generated3inicialwidget1/generated/GeneratedVectorWidget31.dart';

/* Frame 3.Inicial
    Autogenerated by FlutLab FTF Generator
  */
class Generated3InicialWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            clipBehavior: Clip.none, fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 32, 44, 51),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 110.0,
                child: GeneratedRectangle4Widget1(),
              ),
              Positioned(
                left: 25.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 21.0,
                child: GeneratedNotificationWidget6(),
              ),
              Positioned(
                left: 25.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 21.0,
                child: GeneratedNotificationWidget7(),
              ),
              Positioned(
                left: 25.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 30.0,
                child: GeneratedOlalunoWidget1(),
              ),
              Positioned(
                left: 323.0,
                top: 58.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedVectorWidget31(),
              ),
              Positioned(
                left: 18.0,
                top: 193.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 133.0,
                child: GeneratedRectangle5Widget1(),
              ),
              Positioned(
                left: 18.0,
                top: 193.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 87.0,
                child: GeneratedImage1Widget1(),
              ),
              Positioned(
                left: 27.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 227.0,
                height: 23.0,
                child: GeneratedCursodeDesignWidget1(),
              ),
              Positioned(
                left: 313.0,
                top: 295.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 23.0,
                child: Generated200hWidget2(),
              ),
              Positioned(
                left: 18.0,
                top: 348.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 133.0,
                child: GeneratedRectangle6Widget1(),
              ),
              Positioned(
                left: 19.0,
                top: 503.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 133.0,
                child: GeneratedRectangle7Widget3(),
              ),
              Positioned(
                left: 18.0,
                top: 348.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 87.0,
                child: GeneratedImage2Widget1(),
              ),
              Positioned(
                left: 19.0,
                top: 503.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 87.0,
                child: GeneratedImage3Widget1(),
              ),
              Positioned(
                left: 27.0,
                top: 445.0,
                right: null,
                bottom: null,
                width: 227.0,
                height: 23.0,
                child: GeneratedPalestraDesign20Widget1(),
              ),
              Positioned(
                left: 27.0,
                top: 602.0,
                right: null,
                bottom: null,
                width: 227.0,
                height: 23.0,
                child: GeneratedCursodeDesignAplicadoWidget2(),
              ),
              Positioned(
                left: 320.0,
                top: 450.0,
                right: null,
                bottom: null,
                width: 29.0,
                height: 23.0,
                child: Generated20hWidget3(),
              ),
              Positioned(
                left: 320.0,
                top: 607.0,
                right: null,
                bottom: null,
                width: 29.0,
                height: 23.0,
                child: Generated20hWidget4(),
              ),
              Positioned(
                left: 19.0,
                top: 651.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 133.0,
                child: GeneratedRectangle8Widget1(),
              ),
              Positioned(
                left: 19.0,
                top: 651.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 87.0,
                child: GeneratedImage4Widget(),
              ),
              Positioned(
                left: 29.0,
                top: 868.0,
                right: null,
                bottom: null,
                width: 227.0,
                height: 23.0,
                child: GeneratedCursodeDesignAplicadoWidget3(),
              ),
              Positioned(
                left: 322.0,
                top: 873.0,
                right: null,
                bottom: null,
                width: 29.0,
                height: 23.0,
                child: Generated20hWidget5(),
              ),
              Positioned(
                left: 19.0,
                top: 153.0,
                right: null,
                bottom: null,
                width: 334.0,
                height: 1.0,
                child: GeneratedLine1Widget1(),
              ),
              Positioned(
                left: 10.0,
                top: 29.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 31.0,
                child: GeneratedArrowbackiosWidget2(),
              ),
              Positioned(
                left: 29.0,
                top: 753.0,
                right: null,
                bottom: null,
                width: 227.0,
                height: 23.0,
                child: GeneratedEstgionoobrigatrioWidget(),
              ),
              Positioned(
                left: 316.0,
                top: 755.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 23.0,
                child: Generated200hWidget3(),
              ),
              Positioned(
                left: 278.0,
                top: 288.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedVectorWidget34(),
              ),
              Positioned(
                left: 278.0,
                top: 445.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedVectorWidget35(),
              ),
              Positioned(
                left: 278.0,
                top: 598.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedVectorWidget36(),
              ),
              Positioned(
                left: 278.0,
                top: 746.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedVectorWidget37(),
              )
            ]),
      ),
    ));
  }
}
